export const events = [
  {
    title: "Next.js Conf 2025",
    image: "/images/event1.png",
    slug: "nextjs-conf-2025",
    date: "2025-10-24",
    location: "San Francisco, CA",
    description: "The global conference for Next.js developers to share, learn, and build together.",
    time: "09:00 AM",
  },
  {
    title: "React Universe",
    image: "/images/event2.png",
    slug: "react-universe",
    date: "2025-11-15",
    location: "Amsterdam, NL",
    description: "Gathering the React community from around the world for a week of talks and workshops.",
    time: "10:00 AM",
  },
  {
    title: "AI Engineers Summit",
    image: "/images/event3.png",
    slug: "ai-engineers-summit",
    date: "2025-12-01",
    location: "Online",
    description: "Where AI engineers come to learn about the latest in LLMs, agents, and more.",
    time: "01:00 PM",
  },
  {
    title: "Global Hackathon Series",
    image: "/images/event4.png",
    slug: "global-hackathon-series",
    date: "2026-01-20",
    location: "Tokyo, JP",
    description: "Build the future with developers from everywhere in this 48-hour hackathon.",
    time: "08:00 AM",
  },
  {
    title: "Web Performance Meetup",
    image: "/images/event5.png",
    slug: "web-perf-meetup",
    date: "2026-02-10",
    location: "Berlin, DE",
    description: "Deep dive into web performance optimization techniques and tools.",
    time: "06:00 PM",
  },
  {
    title: "Open Source Day",
    image: "/images/event6.png",
    slug: "open-source-day",
    date: "2026-03-05",
    location: "Seattle, WA",
    description: "Celebrating open source contributions and maintainers.",
    time: "11:00 AM",
  },
];
